service: cloud-resume-challenge

provider:
  name: aws
  region: us-east-2
  ecr:
    images:
      appimage:
        path: ./

functions:
  app:
    image:
      name: appimage
    timeout: 30
    events:
      - http: 
          path: ANY /
          cors: true
      - http:
          path: 'ANY /{proxy+}'
          cors: true
